version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  inventory-api:
    build:
      context: .
      dockerfile: Inventory.API/Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__VirtualHost=/
      - RabbitMQ__ExchangeName=inventory_exchange
      - ConnectionStrings__DefaultConnection=Data Source=/shared/inventory.db
    volumes:
      - shared-sqlite:/shared

  notification-service:
    build:
      context: .
      dockerfile: Notification.Service/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__VirtualHost=/
      - ConnectionStrings__DefaultConnection=Data Source=/shared/inventory.db
    volumes:
      - shared-sqlite:/shared

volumes:
  shared-sqlite:
    driver: local